// ui/src/components/ModelsModal.tsx
import React, { useState, useEffect, useCallback } from "react";
import Modal from "./Modal";
import { useI18n } from "../i18n";
import {
  api,
  AvailableModel,
  customModelsApi,
  CustomModel,
  CreateCustomModelRequest,
  TestCustomModelRequest,
} from "../services/api";

interface ModelsModalProps {
  isOpen: boolean;
  onClose: () => void;
  onModelsChanged?: () => void;
}

type ProviderType = "anthropic" | "openai" | "openai-responses" | "gemini";

const DEFAULT_ENDPOINTS: Record<ProviderType, string> = {
  anthropic: "https://api.anthropic.com/v1/messages",
  openai: "https://api.openai.com/v1",
  "openai-responses": "https://api.openai.com/v1",
  gemini: "https://generativelanguage.googleapis.com/v1beta",
};

const PROVIDER_LABELS: Record<ProviderType, string> = {
  anthropic: "Anthropic",
  openai: "OpenAI (Chat API)",
  "openai-responses": "OpenAI (Responses API)",
  gemini: "Google Gemini",
};

const DEFAULT_MODELS: Record<ProviderType, { name: string; model_name: string }[]> = {
  anthropic: [
    { name: "Claude Sonnet 4.6", model_name: "claude-sonnet-4-6" },
    { name: "Claude Opus 4.6", model_name: "claude-opus-4-6" },
    { name: "Claude Haiku 4.5", model_name: "claude-haiku-4-5" },
  ],
  openai: [
    { name: "GPT-5.3 Chat", model_name: "gpt-5.3-chat-latest" },
    { name: "GPT-5.5", model_name: "gpt-5.5" },
    { name: "GPT-5.4", model_name: "gpt-5.4" },
  ],
  "openai-responses": [
    { name: "GPT-5.5", model_name: "gpt-5.5" },
    { name: "GPT-5.4", model_name: "gpt-5.4" },
    { name: "GPT-5.4 mini", model_name: "gpt-5.4-mini" },
    { name: "GPT-5.3 Codex", model_name: "gpt-5.3-codex" },
  ],
  gemini: [
    { name: "Gemini 3 Pro", model_name: "gemini-3-pro-preview" },
    { name: "Gemini 3 Flash", model_name: "gemini-3-flash-preview" },
  ],
};

// Built-in model info from init data
type BuiltInModel = AvailableModel;

// API_TYPE_LABELS maps the wire-protocol enum values from server-side
// models.APIType to the same human-readable strings the custom-model form
// shows for its Provider/API Format field.
const API_TYPE_LABELS: Record<string, string> = {
  "anthropic-messages": "Anthropic",
  "openai-chat-completions": "OpenAI (Chat API)",
  "openai-responses": "OpenAI (Responses API)",
  gemini: "Google Gemini",
  builtin: "Built-in",
};

interface FormData {
  display_name: string;
  provider_type: ProviderType;
  endpoint: string;
  endpoint_custom: boolean;
  api_key: string;
  model_name: string;
  max_tokens: number;
  tags: string; // Comma-separated tags
  reasoning_effort: string; // Free-form reasoning.effort for OpenAI Responses API
  image_support: "auto" | "yes" | "no";
}

const emptyForm: FormData = {
  display_name: "",
  provider_type: "anthropic",
  endpoint: DEFAULT_ENDPOINTS.anthropic,
  endpoint_custom: false,
  api_key: "",
  model_name: "",
  max_tokens: 200000,
  tags: "",
  reasoning_effort: "",
  image_support: "auto",
};

// Common reasoning.effort values for the OpenAI Responses API. Free-form so
// users can type anything providers add later.
const REASONING_EFFORT_SUGGESTIONS = ["none", "minimal", "low", "medium", "high", "xhigh"];

type ImageSupportIndicatorProps =
  | { mode: "resolved"; resolved: boolean }
  | { mode: "custom"; imageSupport: "auto" | "yes" | "no" };

function ImageSupportIndicator(props: ImageSupportIndicatorProps) {
  const { t } = useI18n();
  let kind: "yes" | "no" | "auto";
  if (props.mode === "resolved") {
    kind = props.resolved ? "yes" : "no";
  } else {
    kind = props.imageSupport;
  }
  if (kind === "yes") {
    return (
      <span
        className="models-table-image-yes"
        role="img"
        title={t("imageSupportYes")}
        aria-label={t("imageSupportYes")}
      >
        ✓
      </span>
    );
  }
  if (kind === "no") {
    return (
      <span
        className="models-table-image-no"
        role="img"
        title={t("imageSupportNo")}
        aria-label={t("imageSupportNo")}
      >
        ✕
      </span>
    );
  }
  return (
    <span
      className="models-table-image-auto"
      role="img"
      title={t("imageSupportAuto")}
      aria-label={t("imageSupportAuto")}
    >
      {t("imageSupportAutoShort")}
    </span>
  );
}

function ModelsModal({ isOpen, onClose, onModelsChanged }: ModelsModalProps) {
  const { t } = useI18n();
  const [models, setModels] = useState<CustomModel[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [builtInModels, setBuiltInModels] = useState<BuiltInModel[]>([]);

  // Form state
  const [showForm, setShowForm] = useState(false);
  const [editingModelId, setEditingModelId] = useState<string | null>(null);
  const [form, setForm] = useState<FormData>(emptyForm);

  // Test state
  const [testing, setTesting] = useState(false);
  const [testResult, setTestResult] = useState<{ success: boolean; message: string } | null>(null);

  // Tooltip state
  const [showTagsTooltip, setShowTagsTooltip] = useState(false);

  const loadModels = useCallback(async () => {
    try {
      setLoading(true);
      setError(null);
      const result = await customModelsApi.getCustomModels();
      setModels(result);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to load models");
    } finally {
      setLoading(false);
    }
  }, []);

  const setBuiltInFromModelList = useCallback((modelList: AvailableModel[]) => {
    setBuiltInModels(modelList.filter((m) => m.source && m.source !== "custom"));
  }, []);

  useEffect(() => {
    if (isOpen) {
      loadModels();
      // Get built-in models from init data (those with non-custom source)
      const initData = window.__SHELLEY_INIT__;
      if (initData?.models) {
        setBuiltInFromModelList(initData.models);
      }
    }
  }, [isOpen, loadModels, setBuiltInFromModelList]);

  const handleProviderChange = (provider: ProviderType) => {
    setForm((prev) => ({
      ...prev,
      provider_type: provider,
      endpoint: prev.endpoint_custom ? prev.endpoint : DEFAULT_ENDPOINTS[provider],
    }));
  };

  const handleEndpointModeChange = (custom: boolean) => {
    setForm((prev) => ({
      ...prev,
      endpoint_custom: custom,
      endpoint: custom ? prev.endpoint : DEFAULT_ENDPOINTS[prev.provider_type],
    }));
  };

  const handleTest = async () => {
    // Need model_name always, and either api_key or editing an existing model
    if (!form.model_name) {
      setTestResult({ success: false, message: t("modelNameRequired") });
      return;
    }
    if (!form.api_key && !editingModelId) {
      setTestResult({ success: false, message: t("apiKeyRequired") });
      return;
    }

    setTesting(true);
    setTestResult(null);

    try {
      const request: TestCustomModelRequest = {
        model_id: editingModelId || undefined, // Pass model_id to use stored key
        provider_type: form.provider_type,
        endpoint: form.endpoint,
        api_key: form.api_key,
        model_name: form.model_name,
        reasoning_effort: form.reasoning_effort,
      };
      const result = await customModelsApi.testCustomModel(request);
      setTestResult(result);
    } catch (err) {
      setTestResult({
        success: false,
        message: err instanceof Error ? err.message : "Test failed",
      });
    } finally {
      setTesting(false);
    }
  };

  const handleSave = async () => {
    if (!form.display_name || !form.api_key || !form.model_name) {
      setError("Display name, API key, and model name are required");
      return;
    }

    try {
      setError(null);
      const request: CreateCustomModelRequest = {
        display_name: form.display_name,
        provider_type: form.provider_type,
        endpoint: form.endpoint,
        api_key: form.api_key,
        model_name: form.model_name,
        max_tokens: form.max_tokens,
        tags: form.tags,
        reasoning_effort: form.reasoning_effort,
        image_support: form.image_support,
      };

      if (editingModelId) {
        await customModelsApi.updateCustomModel(editingModelId, request);
      } else {
        await customModelsApi.createCustomModel(request);
      }

      setShowForm(false);
      setEditingModelId(null);
      setForm(emptyForm);
      setTestResult(null);
      await loadModels();
      onModelsChanged?.();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to save model");
    }
  };

  const handleEdit = (model: CustomModel) => {
    setEditingModelId(model.model_id);
    setForm({
      display_name: model.display_name,
      provider_type: model.provider_type,
      endpoint: model.endpoint,
      endpoint_custom: model.endpoint !== DEFAULT_ENDPOINTS[model.provider_type],
      api_key: model.api_key,
      model_name: model.model_name,
      max_tokens: model.max_tokens,
      tags: model.tags,
      reasoning_effort: model.reasoning_effort || "",
      image_support: model.image_support ?? "auto",
    });
    setShowForm(true);
    setTestResult(null);
  };

  const handleDuplicate = async (model: CustomModel) => {
    try {
      setError(null);
      await customModelsApi.duplicateCustomModel(model.model_id);
      await loadModels();
      onModelsChanged?.();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to duplicate model");
    }
  };

  const handleDelete = async (modelId: string) => {
    try {
      setError(null);
      await customModelsApi.deleteCustomModel(modelId);
      await loadModels();
      onModelsChanged?.();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to delete model");
    }
  };

  const handleCancel = () => {
    setShowForm(false);
    setEditingModelId(null);
    setForm(emptyForm);
    setTestResult(null);
  };

  const handleAddNew = () => {
    setEditingModelId(null);
    setForm(emptyForm);
    setShowForm(true);
    setTestResult(null);
  };

  const handleRefreshModels = async () => {
    try {
      setRefreshing(true);
      setError(null);
      const refreshedModels = await api.refreshModels();
      if (window.__SHELLEY_INIT__) {
        window.__SHELLEY_INIT__.models = refreshedModels;
      }
      setBuiltInFromModelList(refreshedModels);
      onModelsChanged?.();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to refresh models");
    } finally {
      setRefreshing(false);
    }
  };

  const headerRight = !showForm ? (
    <div className="models-header-actions">
      <button
        className="btn-secondary btn-sm"
        onClick={handleRefreshModels}
        disabled={refreshing || loading}
      >
        {refreshing ? t("refreshingModels") : t("refreshModels")}
      </button>
      <button className="btn-primary btn-sm" onClick={handleAddNew}>
        + {t("addModel")}
      </button>
    </div>
  ) : null;

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title={t("manageModels")}
      titleRight={headerRight}
      className="modal-xwide"
    >
      <div className="models-modal">
        {error && (
          <div className="models-error">
            {error}
            <button onClick={() => setError(null)} className="models-error-dismiss">
              ×
            </button>
          </div>
        )}

        {loading ? (
          <div className="models-loading">
            <div className="spinner"></div>
            <span>{t("loadingModels")}</span>
          </div>
        ) : showForm ? (
          // Add/Edit form
          <div className="model-form">
            <h3>{editingModelId ? t("editModel") : t("addModel")}</h3>

            {/* Provider Selection */}
            <div className="form-group">
              <label>{t("providerApiFormat")}</label>
              <div className="provider-buttons">
                {(["anthropic", "openai", "openai-responses", "gemini"] as ProviderType[]).map(
                  (p) => (
                    <button
                      key={p}
                      type="button"
                      className={`provider-btn ${form.provider_type === p ? "selected" : ""}`}
                      onClick={() => handleProviderChange(p)}
                    >
                      {PROVIDER_LABELS[p]}
                    </button>
                  ),
                )}
              </div>
            </div>

            {/* Endpoint Selection */}
            <div className="form-group">
              <label>{t("endpoint")}</label>
              <div className="endpoint-toggle">
                <button
                  type="button"
                  className={`toggle-btn ${!form.endpoint_custom ? "selected" : ""}`}
                  onClick={() => handleEndpointModeChange(false)}
                >
                  {t("defaultEndpoint")}
                </button>
                <button
                  type="button"
                  className={`toggle-btn ${form.endpoint_custom ? "selected" : ""}`}
                  onClick={() => handleEndpointModeChange(true)}
                >
                  {t("customEndpoint")}
                </button>
              </div>
              {form.endpoint_custom ? (
                <input
                  type="text"
                  value={form.endpoint}
                  onChange={(e) => setForm((prev) => ({ ...prev, endpoint: e.target.value }))}
                  placeholder="https://..."
                  className="form-input"
                />
              ) : (
                <div className="endpoint-display">{form.endpoint}</div>
              )}
            </div>

            {/* Model Name with autocomplete suggestions */}
            <div className="form-group">
              <label>{t("model")}</label>
              <input
                type="text"
                value={form.model_name}
                onChange={(e) => {
                  const v = e.target.value;
                  setForm((prev) => {
                    // If the user picked a known suggestion and the display
                    // name is empty, pre-fill it from the preset's friendly
                    // name. Never overwrite a non-empty display name.
                    const preset = DEFAULT_MODELS[prev.provider_type].find(
                      (p) => p.model_name === v,
                    );
                    return {
                      ...prev,
                      model_name: v,
                      display_name: preset && !prev.display_name ? preset.name : prev.display_name,
                    };
                  });
                }}
                placeholder="Model name (e.g., claude-sonnet-4-6)"
                className="form-input"
                list={`model-name-suggestions-${form.provider_type}`}
                autoComplete="off"
              />
              <datalist id={`model-name-suggestions-${form.provider_type}`}>
                {DEFAULT_MODELS[form.provider_type].map((preset) => (
                  <option key={preset.model_name} value={preset.model_name}>
                    {preset.name}
                  </option>
                ))}
              </datalist>
            </div>

            {/* Display Name */}
            <div className="form-group">
              <label>{t("displayName")}</label>
              <input
                type="text"
                value={form.display_name}
                onChange={(e) => setForm((prev) => ({ ...prev, display_name: e.target.value }))}
                placeholder={t("nameShownInSelector")}
                className="form-input"
              />
            </div>

            {/* API Key */}
            <div className="form-group">
              <label>{t("apiKey")}</label>
              <input
                type="text"
                value={form.api_key}
                onChange={(e) => setForm((prev) => ({ ...prev, api_key: e.target.value }))}
                placeholder={t("enterApiKey")}
                className="form-input"
                autoComplete="off"
              />
            </div>

            {/* Max Tokens */}
            <div className="form-group">
              <label>{t("maxContextTokens")}</label>
              <input
                type="number"
                value={form.max_tokens}
                onChange={(e) =>
                  setForm((prev) => ({ ...prev, max_tokens: parseInt(e.target.value) || 200000 }))
                }
                className="form-input"
              />
            </div>

            {/* Image input support */}
            <div className="form-group">
              <label>{t("imageSupport")}</label>
              <select
                value={form.image_support}
                onChange={(e) =>
                  setForm((prev) => ({
                    ...prev,
                    image_support: e.target.value as "auto" | "yes" | "no",
                  }))
                }
                className="form-input"
              >
                <option value="auto">{t("imageSupportAuto")}</option>
                <option value="yes">{t("imageSupportYes")}</option>
                <option value="no">{t("imageSupportNo")}</option>
              </select>
              <div className="form-hint">{t("imageSupportHelp")}</div>
            </div>

            {/* Reasoning Effort (OpenAI Responses API only) */}
            {form.provider_type === "openai-responses" && (
              <div className="form-group">
                <label>{t("reasoningEffort")}</label>
                <input
                  type="text"
                  value={form.reasoning_effort}
                  onChange={(e) =>
                    setForm((prev) => ({ ...prev, reasoning_effort: e.target.value }))
                  }
                  placeholder={t("reasoningEffortPlaceholder")}
                  className="form-input"
                  list="reasoning-effort-suggestions"
                  autoComplete="off"
                />
                <datalist id="reasoning-effort-suggestions">
                  {REASONING_EFFORT_SUGGESTIONS.map((suggestion) => (
                    <option key={suggestion} value={suggestion} />
                  ))}
                </datalist>
                <div className="form-hint">{t("reasoningEffortHint")}</div>
              </div>
            )}

            {/* Tags */}
            <div className="form-group">
              <label>
                {t("tags")}
                <span
                  className="info-icon-wrapper"
                  onClick={(e) => {
                    e.preventDefault();
                    e.stopPropagation();
                    setShowTagsTooltip(!showTagsTooltip);
                  }}
                >
                  <span className="info-icon">
                    <svg
                      fill="none"
                      stroke="currentColor"
                      viewBox="0 0 24 24"
                      width="14"
                      height="14"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                      />
                    </svg>
                  </span>
                  {showTagsTooltip && <span className="info-tooltip">{t("tagsTooltip")}</span>}
                </span>
              </label>
              <input
                type="text"
                value={form.tags}
                onChange={(e) => setForm((prev) => ({ ...prev, tags: e.target.value }))}
                placeholder={t("tagsPlaceholder")}
                className="form-input"
              />
            </div>

            {/* Test Result */}
            {testResult && (
              <div className={`test-result ${testResult.success ? "success" : "error"}`}>
                {testResult.success ? "✓" : "✗"} {testResult.message}
              </div>
            )}

            {/* Form Actions */}
            <div className="form-actions">
              <button type="button" className="btn-secondary" onClick={handleCancel}>
                {t("cancel")}
              </button>
              <button
                type="button"
                className="btn-secondary"
                onClick={handleTest}
                disabled={testing || (!form.api_key && !editingModelId) || !form.model_name}
                title={
                  !form.model_name
                    ? "Enter model name to test"
                    : !form.api_key && !editingModelId
                      ? "Enter API key to test"
                      : ""
                }
              >
                {testing ? t("testingButton") : t("testButton")}
              </button>
              <button
                type="button"
                className="btn-primary"
                onClick={handleSave}
                disabled={!form.display_name || !form.api_key || !form.model_name}
              >
                {editingModelId ? t("save") : t("addModel")}
              </button>
            </div>
          </div>
        ) : // Model List
        builtInModels.length === 0 && models.length === 0 ? (
          <div className="models-empty">
            <p>{t("noModelsConfigured")}</p>
            <p className="models-empty-hint">{t("noModelsHint")}</p>
          </div>
        ) : (
          <div className="models-modal-scroll">
            <table className="models-table">
              <thead>
                <tr>
                  <th>{t("columnName")}</th>
                  <th>{t("columnModelId")}</th>
                  <th>{t("columnProvider")}</th>
                  <th>{t("columnSource")}</th>
                  <th>{t("endpoint")}</th>
                  <th>{t("tags")}</th>
                  <th className="models-table-images-col">{t("columnImages")}</th>
                  <th className="models-table-actions-col">
                    <span className="sr-only">{t("columnActions")}</span>
                  </th>
                </tr>
              </thead>
              <tbody>
                {builtInModels
                  .filter((m) => m.id !== "predictable")
                  .map((model) => (
                    <tr key={model.id} className="models-table-row models-table-row-builtin">
                      <td className="models-table-name">{model.display_name || model.id}</td>
                      <td className="models-table-mono">{model.id}</td>
                      <td
                        className={
                          model.api_type && API_TYPE_LABELS[model.api_type]
                            ? undefined
                            : "models-table-muted"
                        }
                      >
                        {(model.api_type && API_TYPE_LABELS[model.api_type]) || "—"}
                      </td>
                      <td>{model.source}</td>
                      <td
                        className={model.base_url ? "models-table-endpoint" : "models-table-muted"}
                        title={model.base_url || undefined}
                      >
                        {model.base_url || "—"}
                      </td>
                      <td className="models-table-muted">—</td>
                      <td className="models-table-images">
                        <ImageSupportIndicator
                          mode="resolved"
                          resolved={model.supports_images ?? true}
                        />
                      </td>
                      <td className="models-table-actions"></td>
                    </tr>
                  ))}
                {models.map((model) => (
                  <tr key={model.model_id} className="models-table-row">
                    <td className="models-table-name">{model.display_name}</td>
                    <td className="models-table-mono">{model.model_name}</td>
                    <td>{PROVIDER_LABELS[model.provider_type]}</td>
                    <td className="models-table-muted">custom</td>
                    <td className="models-table-endpoint" title={model.endpoint}>
                      {model.endpoint}
                    </td>
                    <td className="models-table-tags" title={model.tags || undefined}>
                      {model.tags || "—"}
                    </td>
                    <td className="models-table-images">
                      <ImageSupportIndicator
                        mode="custom"
                        imageSupport={model.image_support ?? "auto"}
                      />
                    </td>
                    <td className="models-table-actions">
                      <button
                        className="btn-icon"
                        onClick={() => handleDuplicate(model)}
                        title={t("duplicate")}
                      >
                        <svg
                          fill="none"
                          stroke="currentColor"
                          viewBox="0 0 24 24"
                          width="16"
                          height="16"
                        >
                          <path
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            strokeWidth={2}
                            d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"
                          />
                        </svg>
                      </button>
                      <button
                        className="btn-icon"
                        onClick={() => handleEdit(model)}
                        title={t("editModel")}
                      >
                        <svg
                          fill="none"
                          stroke="currentColor"
                          viewBox="0 0 24 24"
                          width="16"
                          height="16"
                        >
                          <path
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            strokeWidth={2}
                            d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"
                          />
                        </svg>
                      </button>
                      <button
                        className="btn-icon btn-danger"
                        onClick={() => handleDelete(model.model_id)}
                        title={t("delete_")}
                      >
                        <svg
                          fill="none"
                          stroke="currentColor"
                          viewBox="0 0 24 24"
                          width="16"
                          height="16"
                        >
                          <path
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            strokeWidth={2}
                            d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"
                          />
                        </svg>
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </Modal>
  );
}

export default ModelsModal;

// ui/src/vue/components/ModelsModal.vue
<!-- Manage Models: lists built-in + custom models and owns duplicate/delete +
     refresh. The list is a compact PrimeVue DataTable (size="small" +
     modelsTableDt tokens) fed by one `tableRows` computed that merges built-in
     and custom models; only custom rows carry a `model` and thus the edit/
     duplicate/delete actions. Adding/editing opens ModelFormModal — a separate
     stacked dialog layered on top of this one — rather than swapping the list
     out in place. Uses Modal.vue (#title-right slot), useI18n, customModelsApi;
     shared form constants live in customModelConstants.ts. -->
<template>
  <Modal
    :is-open="isOpen"
    :title="t('manageModels')"
    class-name="modal-xwide"
    @close="emit('close')"
  >
    <template #title-right>
      <div class="models-header-actions">
        <button
          class="btn-secondary btn-sm"
          :disabled="refreshing || loading"
          @click="handleRefreshModels"
        >
          {{ refreshing ? t("refreshingModels") : t("refreshModels") }}
        </button>
        <button class="btn-primary btn-sm" @click="handleAddNew">+ {{ t("addModel") }}</button>
      </div>
    </template>

    <div class="models-modal" :class="{ 'models-modal-list': showList }">
      <div v-if="error" class="models-error">
        {{ error }}
        <button class="models-error-dismiss" @click="error = null">×</button>
      </div>

      <div v-if="loading" class="models-loading">
        <div class="spinner"></div>
        <span>{{ t("loadingModels") }}</span>
      </div>

      <!-- Empty state -->
      <div v-else-if="builtInModels.length === 0 && models.length === 0" class="models-empty">
        <p>{{ t("noModelsConfigured") }}</p>
        <p class="models-empty-hint">{{ t("noModelsHint") }}</p>
      </div>

      <!-- Model List -->
      <DataTable
        v-else
        :value="tableRows"
        data-key="key"
        size="small"
        scrollable
        scroll-height="flex"
        :dt="modelsTableDt"
        class="models-datatable"
      >
        <Column :header="t('columnName')" field="name">
          <template #body="{ data }">
            <span class="models-cell-name">{{ data.name }}</span>
          </template>
        </Column>
        <Column :header="t('columnModelId')" field="modelId">
          <template #body="{ data }">
            <span class="models-cell-mono">{{ data.modelId }}</span>
          </template>
        </Column>
        <Column :header="t('columnProvider')" field="apiShape">
          <template #body="{ data }">
            <span :class="{ 'models-cell-muted': !data.apiShape }">{{ data.apiShape || "—" }}</span>
          </template>
        </Column>
        <Column :header="t('columnSource')" field="source">
          <template #body="{ data }">
            <span :class="{ 'models-cell-muted': data.source === 'custom' }">{{ data.source }}</span>
          </template>
        </Column>
        <Column :header="t('endpoint')" field="endpoint">
          <template #body="{ data }">
            <span
              v-if="data.endpoint"
              class="models-cell-endpoint"
              :title="data.endpoint"
              >{{ data.endpoint }}</span
            >
            <span v-else class="models-cell-muted">—</span>
          </template>
        </Column>
        <Column :header="t('tags')" field="tags">
          <template #body="{ data }">
            <span v-if="data.tags" class="models-cell-tags" :title="data.tags">{{ data.tags }}</span>
            <span v-else class="models-cell-muted">—</span>
          </template>
        </Column>
        <Column :header="t('columnImages')" field="supportsImages" class="models-col-images">
          <template #body="{ data }">
            <span
              :class="data.supportsImages ? 'models-table-image-yes' : 'models-table-image-no'"
              role="img"
              :title="data.imageTitle"
              :aria-label="data.imageTitle"
              >{{ data.supportsImages ? "✓" : "✕"
              }}<span v-if="data.imageAuto" class="models-table-image-auto-tag">{{
                t("imageSupportAutoShort")
              }}</span></span
            >
          </template>
        </Column>
        <Column class="models-col-actions">
          <template #header>
            <span class="sr-only">{{ t("columnActions") }}</span>
          </template>
          <template #body="{ data }">
            <div v-if="data.model" class="models-cell-actions">
              <button
                class="btn-icon"
                v-tooltip.top="t('duplicate')"
                :aria-label="t('duplicate')"
                @click="handleDuplicate(data.model)"
              >
                <svg fill="none" stroke="currentColor" viewBox="0 0 24 24" width="16" height="16">
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    :stroke-width="2"
                    d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"
                  />
                </svg>
              </button>
              <button
                class="btn-icon"
                v-tooltip.top="t('editModel')"
                :aria-label="t('editModel')"
                @click="handleEdit(data.model)"
              >
                <svg fill="none" stroke="currentColor" viewBox="0 0 24 24" width="16" height="16">
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    :stroke-width="2"
                    d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"
                  />
                </svg>
              </button>
              <button
                class="btn-icon btn-danger"
                v-tooltip.top="t('delete_')"
                :aria-label="t('delete_')"
                @click="handleDelete(data.model.model_id)"
              >
                <svg fill="none" stroke="currentColor" viewBox="0 0 24 24" width="16" height="16">
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    :stroke-width="2"
                    d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"
                  />
                </svg>
              </button>
            </div>
          </template>
        </Column>
      </DataTable>
    </div>
  </Modal>

  <!-- Stacked add/edit dialog, layered on top of the list. -->
  <ModelFormModal
    :is-open="formOpen"
    :edit-model="editModel"
    @saved="handleFormSaved"
    @close="formOpen = false"
  />
</template>

<script setup lang="ts">
import { computed, ref, watch } from "vue";
import DataTable from "primevue/datatable";
import Column from "primevue/column";
import Modal from "./Modal.vue";
import ModelFormModal from "./ModelFormModal.vue";
import { modelsTableDt } from "./modelsTableDt";
import { API_TYPE_LABELS, PROVIDER_LABELS } from "./customModelConstants";
import { useI18n } from "../composables/i18n";
import { api, customModelsApi, type AvailableModel, type CustomModel } from "../../services/api";

const props = defineProps<{ isOpen: boolean }>();
const emit = defineEmits<{ (e: "close"): void; (e: "modelsChanged"): void }>();

const { t } = useI18n();

const models = ref<CustomModel[]>([]);
const loading = ref(true);
const refreshing = ref(false);
const error = ref<string | null>(null);
const builtInModels = ref<AvailableModel[]>([]);

// Stacked add/edit dialog state. `editModel` is the custom model being edited,
// or null when adding a new one.
const formOpen = ref(false);
const editModel = ref<CustomModel | null>(null);

const builtInModelsFiltered = computed(() =>
  builtInModels.value.filter((m) => m.id !== "predictable"),
);

// True when the model-list DataTable (not the empty/loading views) is showing.
// The list fills the modal edge-to-edge, so we drop the wrapper padding in that
// state (see .models-modal-list).
const showList = computed(
  () => !loading.value && (builtInModels.value.length > 0 || models.value.length > 0),
);

// Normalized rows so built-in + custom models render through one DataTable.
// `model` is only present for custom rows, which are the editable/deletable
// ones (built-ins have no actions).
interface TableRow {
  key: string;
  name: string;
  modelId: string;
  apiShape: string | null;
  source: string;
  endpoint: string;
  tags: string;
  supportsImages: boolean;
  imageTitle: string;
  imageAuto: boolean;
  model: CustomModel | null;
}

const tableRows = computed<TableRow[]>(() => {
  const builtin: TableRow[] = builtInModelsFiltered.value.map((m) => ({
    key: `builtin:${m.id}`,
    name: m.display_name || m.id,
    modelId: m.id,
    apiShape: (m.api_type && API_TYPE_LABELS[m.api_type]) || null,
    source: m.source || "",
    endpoint: m.base_url || "",
    tags: "",
    supportsImages: m.supports_images ?? true,
    imageTitle: (m.supports_images ?? true) ? t("imageSupportYes") : t("imageSupportNo"),
    imageAuto: false,
    model: null,
  }));
  const custom: TableRow[] = models.value.map((m) => ({
    key: `custom:${m.model_id}`,
    name: m.display_name,
    modelId: m.model_name,
    apiShape: PROVIDER_LABELS[m.provider_type],
    source: "custom",
    endpoint: m.endpoint,
    tags: m.tags || "",
    supportsImages: customModelSupportsImages(m),
    imageTitle: customModelImageTitle(m),
    imageAuto: (m.image_support ?? "auto") === "auto",
    model: m,
  }));
  return [...builtin, ...custom];
});

// For a custom model, the boolean its image_support setting evaluates to. When
// set to "auto" we use the server-resolved supports_images; explicit yes/no win.
function customModelSupportsImages(model: CustomModel): boolean {
  const setting = model.image_support ?? "auto";
  if (setting === "yes") return true;
  if (setting === "no") return false;
  return model.supports_images ?? true;
}

function customModelImageTitle(model: CustomModel): string {
  const label = customModelSupportsImages(model) ? t("imageSupportYes") : t("imageSupportNo");
  // Surface what auto resolved to for auto models.
  if ((model.image_support ?? "auto") === "auto") {
    return `${t("imageSupportAuto")} \u2014 ${label}`;
  }
  return label;
}

async function loadModels() {
  try {
    loading.value = true;
    error.value = null;
    models.value = await customModelsApi.getCustomModels();
  } catch (err) {
    error.value = err instanceof Error ? err.message : "Failed to load models";
  } finally {
    loading.value = false;
  }
}

function setBuiltInFromModelList(modelList: AvailableModel[]) {
  builtInModels.value = modelList.filter((m) => m.source && m.source !== "custom");
}

function handleAddNew() {
  editModel.value = null;
  formOpen.value = true;
}

function handleEdit(model: CustomModel) {
  editModel.value = model;
  formOpen.value = true;
}

// The stacked form dialog saved a model; reload the list and notify the app.
async function handleFormSaved() {
  await loadModels();
  emit("modelsChanged");
}

async function handleDuplicate(model: CustomModel) {
  try {
    error.value = null;
    await customModelsApi.duplicateCustomModel(model.model_id);
    await loadModels();
    emit("modelsChanged");
  } catch (err) {
    error.value = err instanceof Error ? err.message : "Failed to duplicate model";
  }
}

async function handleDelete(modelId: string) {
  try {
    error.value = null;
    await customModelsApi.deleteCustomModel(modelId);
    await loadModels();
    emit("modelsChanged");
  } catch (err) {
    error.value = err instanceof Error ? err.message : "Failed to delete model";
  }
}

async function handleRefreshModels() {
  try {
    refreshing.value = true;
    error.value = null;
    const refreshedModels = await api.refreshModels();
    if (window.__SHELLEY_INIT__) {
      window.__SHELLEY_INIT__.models = refreshedModels;
    }
    setBuiltInFromModelList(refreshedModels);
    emit("modelsChanged");
  } catch (err) {
    error.value = err instanceof Error ? err.message : "Failed to refresh models";
  } finally {
    refreshing.value = false;
  }
}

watch(
  () => props.isOpen,
  (open) => {
    if (open) {
      loadModels();
      const initData = window.__SHELLEY_INIT__;
      if (initData?.models) {
        setBuiltInFromModelList(initData.models);
      }
    }
  },
  { immediate: true },
);
</script>
